Tourist_VietripInsum_2023/Controllers/ChuBienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Tourist_VietripInsum_2023.Models;
using Tourist_VietripInsum_2023.App_Start;
using System.Data.Entity;

namespace Tourist_VietripInsum_2023.Controllers
{
    [AdminAuthorize(maCV = "CB")]
    public class ChuBienController : Controller
    {
        QuanLyToaSoanEntities database = new QuanLyToaSoanEntities();
        // GET: ChuBien
        public ActionResult Index()
        {
            var dsnhabao = database.NhanViens.Where(s=> s.MaCV == "NB").ToList().Count();
            Session["SoNhaBao"] = dsnhabao;
            var dsdoitac = database.NhanViens.Where(s => s.MaCV == "DT").ToList().Count();
            Session["SoDoiTac"] = dsdoitac;
            var dsbaibao = database.BaiBaos.ToList().Count();
            Session["SoBaiBao"] = dsbaibao;
            var dstheloai = database.TheLoais.ToList().Count();
            Session["SoTheLoai"] = dstheloai;
            return View();
        }

        public ActionResult Delete(string id )
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sp = database.BaiBaos.Where(s => s.MaBaiBao == id).FirstOrDefault();
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BaiBao bao = database.BaiBaos.Where(s => s.MaBaiBao == id).FirstOrDefault();
            database.BaiBaos.Where(s => s.MaBaiBao == id).FirstOrDefault(); database.BaiBaos.Remove(bao);
            database.SaveChanges();
            TempData["AlertMessage"] = "deleted";
            return Redirect("/ChuBien/IndexQLBaiBao");
        }

        // GET: BaiBaos
        public ActionResult IndexQLBaiBao()
        {
            var baiBaos = database.BaiBaos.ToList();
            return View(baiBaos.ToList());
        }

        // GET: BaiBaos/Details/5
        public ActionResult DetailsBaiBao(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiBao baiBao = database.BaiBaos.Find(id);
            if (baiBao == null)
            {
                return HttpNotFound();
            }
            return View(baiBao);
        }

        // POST: BaiBaos/DuyetBai/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DuyetBai(string idBaiBao, bool flag)
        {
            if (!flag) 
                TempData["AlertMessage"] = "false";
            else
                TempData["AlertMessage"] = "true";
            BaiBao baiBao = database.BaiBaos.Find(idBaiBao);
            baiBao.TrangThaiDuyet = flag;
            if (ModelState.IsValid)
            {
                database.Entry(baiBao).State = EntityState.Modified;
                database.SaveChanges();
                return RedirectToAction("IndexQLBaiBao");
            }
            return View(baiBao);
        }
    }
}

Tourist_VietripInsum_2023/Views/ChuBien/Delete.cshtml
@model Tourist_VietripInsum_2023.Models.BaiBao

@{
    ViewBag.Title = "Quản lý bài báo";
    ViewBag.Name = "Quản lý bài báo / Xóa bài báo";
    ViewBag.qlt = "active";
    Layout = "~/Views/ChuBien/LayoutCB/_LayoutCB.cshtml";
}

<link href="~/Content/Css/managementForm.css" rel="stylesheet" />
<script src="~/Scripts/main.js" language="JavaScript" type="text/javascript"></script>

<div class="box-form">
    <div class="form-horizontal">
        <h4 class="title-form">XOÁ BÀI BÁO - @Model.MaBaiBao</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row p-0">
            <span class="col label-name">Tiêu đề</span>
            <p class="delete-form col-10 m-0">
                @Html.DisplayFor(model => model.TieuDe)
            </p>
        </div>

        <div class="form-group row p-0">
            <span class="col label-name">Nôi dung</span>
            <p class="delete-form col-10 m-0 textArea">
                @Html.DisplayFor(model => model.NoiDung)
            </p>
        </div>

        <div class="form-group row p-0">
            <span class="col label-name">Ngày đăng</span>
            <p class="delete-form col-10 m-0">
                @Html.DisplayFor(model => model.NgayDangBai)
            </p>
        </div>

        <div class="form-group row p-0">
            <span class="col label-name">Thể Loại</span>
            <p class="delete-form col-10 m-0 ">
                @Html.DisplayNameFor(model => model.TheLoai.TenTL)
            </p>
        </div>

        <div class="d-flex justify-content-center form-btn">
            <input id="btn-delete" value="Xoá" class="btn btn-danger" readonly style="width: 100%" />
        </div>
    </div>
</div>
<div>
    @using (Html.BeginForm("Delete", "ChuBien", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("id", Model.MaBaiBao)
        <div style="background: #000">
            <div class="box-confirm box-shadow shadow">
                <h4>Bạn Có Chắc Chắn Xoá?</h4>
                <hr />
                <h3 style="color: red;">Mã bài báo: @Model.MaBaiBao</h3>
                <div class="row mt-4">
                    <input type="submit" value="Xác Nhận Xoá" class="btn btn-danger col-10" readonly style="width: 70%" />
                    <input value="Huỷ" id="btn-cancel" class="btn btn-default col" readonly style="width: 20%" />
                </div>
            </div>
        </div>
    }
</div>
@Html.ActionLink("Back to List", "IndexQLBaiBao")

<script>
    var btnDelete = document.querySelector('#btn-delete');
    var modelBox = document.querySelector('.box-confirm');
    var btnCancel = document.querySelector('#btn-cancel');


    btnDelete.onclick = function () {
        modelBox.style.display = "block";
    }

    btnCancel.onclick = function () {
        modelBox.style.display = "none";
    }

</script>

Tourist_VietripInsum_2023/Views/ChuBien/DetailsBaiBao.cshtml
@model Tourist_VietripInsum_2023.Models.BaiBao
@{
    ViewBag.Title = "Quản lý bài báo";
    ViewBag.Name = "Quản lý bài báo / Chi tiết bài báo";
    ViewBag.qlt = "active";
    Layout = "~/Views/ChuBien/LayoutCB/_LayoutCB.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <div class="tile">
            <h3 class="tile-title">THÔNG TIN BÀI BÁO</h3>
            <div class="tile-body element-button">
                <div class="row">
                    <div class="col-md-4">
                        <img src="@Model.HinhAnhs" width="300" height="300" />
                    </div>
                    <div class="col-md-8">
                        <div style="font-size: 18px;">
                            <div class="form-group" style="text-align: center;">
                                <b>Mã bài báo: </b> @Html.DisplayFor(model => model.MaBaiBao)
                            </div>
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="form-group">
                                        <b>Tiêu đề: </b> @Html.DisplayFor(model => model.TieuDe)
                                    </div>
                                    <div class="form-group">
                                        <b>Tác giả: </b> @Html.DisplayFor(model => model.NhanVien.HoTen)
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <b>Thể loại: </b> @Html.DisplayFor(model => model.TheLoai.TenTL)
                                    </div>
                                    <div class=" form-group">
                                        <b>Ngày đăng bài: </b> @Html.DisplayFor(model => model.NgayDangBai)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <table>
                                    <thead style="background-color: #ffd43b;">
                                        <tr>
                                            <th aria-controls="sampleTable" rowspan="1" colspan="1" style="text-align: center;">Trạng thái duyệt</th>
                                            <th aria-controls="sampleTable" rowspan="1" colspan="1" style="text-align: center;">Trạng thái bài báo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="text-align: center;">
                                                @Html.DisplayFor(model => model.TrangThaiDuyet)
                                            </td>
                                            <td style="text-align: center;">
                                                @Html.DisplayFor(model => model.TrangThaiBaiBao)
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <a href="/ChuBien/IndexQLBaiBao" class="btn btn-outline-primary" style="margin-top:10px;" ata-toggle="tooltip" title="Trở lại">
                    <i class="fas fc-agenda-view"></i> Trở lại
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="tile">
            <h3 class="tile-title">Nội dung</h3>
            <div class="tile-body table-responsive">
                @Html.DisplayFor(model => model.NoiDung)
            </div>
            <div class="row">
                <div class="col-md-6">
                    <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">Duyệt bài</button>
                    <div id="demo" class="collapse">
                        Bạn có chắc là muốn duyệt bài báo này? Sau khi duyệt bài báo sẽ được hiển thị lên website.
                        @using (Html.BeginForm("DuyetBai", "ChuBien", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div>
                                @Html.Hidden("idBaiBao", Model.MaBaiBao)
                                @Html.Hidden("flag", true)
                                <input type="checkbox" id="" name="" value="true" checked disabled />
                                <input type="submit" class="btn btn-outline-success" value="Xác nhận" />
                            </div>
                        }
                    </div>
                </div>
                <div class="col-md-6">
                    <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#demo2">Hủy duyệt</button>
                    <div id="demo2" class="collapse">
                        @using (Html.BeginForm("DuyetBai", "ChuBien", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="control-label col-md-2" for="lydo">Lý do:</label>
                                <div class="col-md-10">
                                    <textarea class="form-control" rows="5" id="lydo" placeholder="Nhập vào lý do" required></textarea>
                                </div>
                            </div>
                            <div>
                                @Html.Hidden("idBaiBao", Model.MaBaiBao)
                                @Html.Hidden("flag", false)
                                <input type="submit" class="btn btn-outline-info" value="Gửi" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

Tourist_VietripInsum_2023/Views/ChuBien/Index.cshtml
@model IEnumerable<Tourist_VietripInsum_2023.Models.BaiBao>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/ChuBien/LayoutCB/_LayoutCB.cshtml"; 
    ViewBag.Name = "HomePage";
    ViewBag.home = "active";
}


@{
    var checkMessage = TempData["AlertMessage"];
    if (checkMessage == "Login sucess")
    {
        <script>
            swal({
                title: "Login success!",
                text: "Welcome to your back!",
                icon: "success",
                button: "OK",
            });
        </script>
    }


}

<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<body>

    <div class="row">
        <!--Thông tin kho và số sản phẩm sắp hết hàng-->
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <!-- col-6 -->
                <div class="col-lg-6 col-xs-12">
                    <a class="widget-small info coloured-icon @ViewBag.qlk" href="#">
                        <i class='icon bx bxs-user-account fa-3x'></i>
                        <div class="info">
                            <h4>Thông tin nhà báo</h4>
                            <p><b>Tổng @TempData["tongTour"] nhà báo được quản lý</b></p>
                            <p class="info-tong">@Convert.ToString(Session["SoNhaBao"])</p>
                        </div>
                    </a>
                </div>
                <!-- col-6 -->
                <div class="col-lg-6 col-xs-12">
                    <a class="widget-small warning coloured-icon @ViewBag.hh" href="#">
                        <i class='icon bx bxs-user-badge fa-3x'></i>
                        <div class="info">
                            <h4>Thông tin đối tác</h4>
                            <p><b>Tổng @TempData["tongLT"] Đối tác</b></p>
                            <p class="info-tong">@Convert.ToString(Session["SoDoiTac"])</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!--Thông tin kho và số sản phẩm sắp hết hàng-->
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <!-- col-6 -->
                <div class="col-lg-6 col-xs-12">
                    <a class="widget-small danger coloured-icon @ViewBag.qlk" href="#">
                        <i class='bx bxs-news fa-3x icon'></i>
                        <div class="info">
                            <h4>Thông tin bài báo</h4>
                            <p><b>Tổng số @TempData["tongDD"] bài báo</b></p>
                            <p class="info-tong">@Convert.ToString(Session["SoBaiBao"])</p>
                        </div>
                    </a>
                </div>
                <!-- col-6 -->
                <div class="col-lg-6 col-xs-12">
                    <a class="widget-small primary coloured-icon @ViewBag.hh" href="#">
                        <i class='bx bxs-category fa-3x icon'></i>
                        <div class="info">
                            <h4>Thể loại bài báo</h4>
                            <p><b>Tổng @TempData["tongTinh"] thể loại bài báo</b></p>
                            <p class="info-tong">@Convert.ToString(Session["SoTheLoai"])</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="tile">
                <h3 class="tile-title">
                    <i class="bx bxs-map"></i>
                    Phạm vi hoạt động (Việt Nam)
                </h3>
                <div class="embed-responsive-item" style="height: 292px">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15739731.94178454!2d96.86731624837675!3d15.607242742130582!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31157a4d736a1e5f%3A0xb03bb0c9e2fe62be!2zVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1677896157419!5m2!1svi!2s" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 ">
            <div class="tile">
                <h3 class="tile-title">
                    Thống kê dữ liệu
                </h3>
                <div>
                    <canvas id="myChart" style="width:100%;"></canvas>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/main.js"></script>

    <script src="~/Scripts/pace.min.js"></script>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script>
        var xValues = ["Nhà báo", "Đối tác", "bài báo", "Thể loại"];
        var yValues = [@Convert.ToString(Session["SoNhaBao"]), @Convert.ToString(Session["SoDoiTac"]), @Convert.ToString(Session["SoBaiBao"]), @Convert.ToString(Session["SoTheLoai"])];
        var barColors = ["red", "green", "blue", "orange", "brown"];

        new Chart("myChart", {
            type: "bar",
            data: {
                labels: xValues,
                datasets: [{
                    backgroundColor: barColors,
                    data: yValues
                }]
            },
            options: {
                legend: { display: false },
                title: {
                    display: true,
                    text: "Thống kê"
                }
            }
        });
    </script>
</body>
</html>